#pragma once
#include <string>
#include <cstdio>
#include <cstring>
#include <cmath>
#include <cstdlib>
#include <sstream>
#include <iostream>
#include <vector>
#include <array>
#include <map>
#include <iomanip>
#include <list>
#include <fstream>
#include <Windows.h>
#include <conio.h>
#include <queue>
#include "stu_info.hpp"
#include "encipher.hpp"
#include "tool.hpp"
#include "service.hpp"
#include "menu.hpp"
using namespace std;
